In [7]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [8]:
%sql postgresql://rahimsharifov:root@localhost:5432/weather

Connecting and switching to connection 'postgresql://rahimsharifov:***@localhost:5432/weather'

In [16]:
import sys
import pandas as pd
from sqlalchemy import create_engine

In [27]:
%%sql

SELECT
*
FROM weather_raw

Running query in 'postgresql://rahimsharifov:***@localhost:5432/weather'

5 rows affected.

+--------------+---------+---------------+--------------+--------------+---------------+------------------+-------------+
|     city     | country | temperature_c | feels_like_c | humidity_pct | wind_speed_ms |   weather_desc   | recorded_at |
+--------------+---------+---------------+--------------+--------------+---------------+------------------+-------------+
|    London    |    GB   |      9.41     |     6.44     |      86      |      6.17     | scattered clouds |  1774822409 |
|   Karaköy    |    TR   |      8.78     |     5.16     |      98      |      7.72     |    light rain    |  1774822625 |
| Cherni Gorod |    AZ   |     10.97     |    10.68     |      98      |      3.12     | overcast clouds  |  1774822159 |
|  Marunouchi  |    JP   |     13.35     |     12.7     |      75      |      2.57     |  broken clouds   |  1774822626 |
|   New York   |    US   |     11.69     |    10.09     |      45      |      7.72     |    few clouds    |  1774822626 |
+--------------+---------+---------------+--------------+--------------+---------------+------------------+-------------+

In [31]:
DB_CONN = "postgresql+psycopg2://rahimsharifov:root@localhost:5432/weather"

engine = create_engine(DB_CONN)
df = pd.read_sql("SELECT * FROM weather_raw", engine)
df.head()

,city,country,temperature_c,feels_like_c,humidity_pct,wind_speed_ms,weather_desc,recorded_at,ingested_at
0,London,GB,9.41,6.44,86,6.17,scattered clouds,1774822409,2026-03-29 22:19:15.949592+00:00
1,Karaköy,TR,8.78,5.16,98,7.72,light rain,1774822625,2026-03-29 22:19:16.411839+00:00
2,Cherni Gorod,AZ,10.97,10.68,98,3.12,overcast clouds,1774822159,2026-03-29 22:19:16.873218+00:00
3,Marunouchi,JP,13.35,12.70,75,2.57,broken clouds,1774822626,2026-03-29 22:19:17.357827+00:00
4,New York,US,11.69,10.09,45,7.72,few clouds,1774822626,2026-03-29 22:19:17.835578+00:00

### Data Inspection

In [29]:
print(f'Shape of extracted data: {df.shape}')

Shape of extracted data: (5, 8)

In [30]:
print(df.dtypes)

city                 str
country              str
temperature_c    float64
feels_like_c     float64
humidity_pct       int64
wind_speed_ms    float64
weather_desc         str
recorded_at        int64
dtype: object

In [24]:
df.isnull().sum()

city             0
country          0
temperature_c    0
feels_like_c     0
humidity_pct     0
wind_speed_ms    0
weather_desc     0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.dropna()

,city,country,temperature_c,feels_like_c,humidity_pct,wind_speed_ms,weather_desc
0,London,GB,8.40,4.67,89,7.72,overcast clouds
1,Karaköy,TR,9.06,6.17,96,5.66,light rain
2,Cherni Gorod,AZ,11.01,10.70,97,3.19,overcast clouds
3,Japan,JP,12.93,12.37,80,4.63,broken clouds
4,New York,US,11.57,9.64,33,8.23,clear sky

#### Handling Missing Values

In [35]:
df.fillna(0)

,city,country,temperature_c,feels_like_c,humidity_pct,wind_speed_ms,weather_desc,recorded_at,ingested_at
0,London,GB,9.41,6.44,86,6.17,scattered clouds,1774822409,2026-03-29 22:19:15.949592+00:00
1,Karaköy,TR,8.78,5.16,98,7.72,light rain,1774822625,2026-03-29 22:19:16.411839+00:00
2,Cherni Gorod,AZ,10.97,10.68,98,3.12,overcast clouds,1774822159,2026-03-29 22:19:16.873218+00:00
3,Marunouchi,JP,13.35,12.70,75,2.57,broken clouds,1774822626,2026-03-29 22:19:17.357827+00:00
4,New York,US,11.69,10.09,45,7.72,few clouds,1774822626,2026-03-29 22:19:17.835578+00:00

In [39]:
df["recorded_at"] = pd.to_datetime(df["recorded_at"], unit="s")
df

,city,country,temperature_c,feels_like_c,humidity_pct,wind_speed_ms,weather_desc,recorded_at,ingested_at
0,London,GB,9.41,6.44,86,6.17,scattered clouds,2026-03-29 22:13:29,2026-03-29 22:19:15.949592+00:00
1,Karaköy,TR,8.78,5.16,98,7.72,light rain,2026-03-29 22:17:05,2026-03-29 22:19:16.411839+00:00
2,Cherni Gorod,AZ,10.97,10.68,98,3.12,overcast clouds,2026-03-29 22:09:19,2026-03-29 22:19:16.873218+00:00
3,Marunouchi,JP,13.35,12.70,75,2.57,broken clouds,2026-03-29 22:17:06,2026-03-29 22:19:17.357827+00:00
4,New York,US,11.69,10.09,45,7.72,few clouds,2026-03-29 22:17:06,2026-03-29 22:19:17.835578+00:00

In [41]:
%%sql 

SELECT *
FROM weather_clean

Running query in 'postgresql://rahimsharifov:***@localhost:5432/weather'

10 rows affected.

+--------------+---------+---------------+--------------+--------------+---------------+------------------+---------------------+----------------------------------+
|     city     | country | temperature_c | feels_like_c | humidity_pct | wind_speed_ms |   weather_desc   |     recorded_at     |           ingested_at            |
+--------------+---------+---------------+--------------+--------------+---------------+------------------+---------------------+----------------------------------+
|    London    |    GB   |      9.2      |     6.17     |      87      |      6.17     | scattered clouds | 2026-03-29 22:24:27 | 2026-03-30 02:30:19.970109+04:00 |
|   Karaköy    |    TR   |      8.98     |     5.42     |      98      |      7.72     |    light rain    | 2026-03-29 22:30:20 | 2026-03-30 02:30:20.462413+04:00 |
| Cherni Gorod |    AZ   |     11.01     |    10.67     |      96      |      3.85     | overcast clouds  | 2026-03-29 22:30:21 | 2026-03-30 02:30:20.982342+04:00 |
|    Japan     |    JP   |      13.3     |    12.62     |      74      |      2.57     |  broken clouds   | 2026-03-29 22:30:08 | 2026-03-30 02:30:21.477958+04:00 |
|   New York   |    US   |     11.51     |     9.89     |      45      |      7.72     |    few clouds    | 2026-03-29 22:29:57 | 2026-03-30 02:30:21.954610+04:00 |
|    London    |    GB   |      6.47     |     5.83     |      82      |      1.34     | scattered clouds | 2026-03-30 05:34:14 | 2026-03-30 09:45:15.108489+04:00 |
|   Karaköy    |    TR   |      8.78     |     5.02     |      98      |      8.23     |    light rain    | 2026-03-30 05:41:48 | 2026-03-30 09:45:15.646834+04:00 |
| Cherni Gorod |    AZ   |     12.97     |    12.65     |      89      |      4.72     |  broken clouds   | 2026-03-30 05:40:53 | 2026-03-30 09:45:16.149379+04:00 |
|    Japan     |    JP   |     20.27     |    19.97     |      62      |      6.69     |  broken clouds   | 2026-03-30 05:45:16 | 2026-03-30 09:45:16.685576+04:00 |
|   New York   |    US   |      7.98     |     5.22     |      64      |      4.63     |    clear sky     | 2026-03-30 05:35:32 | 2026-03-30 09:45:17.212332+04:00 |
+--------------+---------+---------------+--------------+--------------+---------------+------------------+---------------------+----------------------------------+
Truncated to displaylimit of 10.

#### Aggregation

In [71]:
%%sql 

SELECT 
    *,
    DATE(recorded_at)
FROM weather_clean

Running query in 'postgresql://rahimsharifov:***@localhost:5432/weather'

10 rows affected.

+--------------+---------+---------------+--------------+--------------+---------------+------------------+---------------------+----------------------------------+------------+
|     city     | country | temperature_c | feels_like_c | humidity_pct | wind_speed_ms |   weather_desc   |     recorded_at     |           ingested_at            |    date    |
+--------------+---------+---------------+--------------+--------------+---------------+------------------+---------------------+----------------------------------+------------+
|    London    |    GB   |      9.2      |     6.17     |      87      |      6.17     | scattered clouds | 2026-03-29 22:24:27 | 2026-03-30 02:30:19.970109+04:00 | 2026-03-29 |
|   Karaköy    |    TR   |      8.98     |     5.42     |      98      |      7.72     |    light rain    | 2026-03-29 22:30:20 | 2026-03-30 02:30:20.462413+04:00 | 2026-03-29 |
| Cherni Gorod |    AZ   |     11.01     |    10.67     |      96      |      3.85     | overcast clouds  | 2026-03-29 22:30:21 | 2026-03-30 02:30:20.982342+04:00 | 2026-03-29 |
|    Japan     |    JP   |      13.3     |    12.62     |      74      |      2.57     |  broken clouds   | 2026-03-29 22:30:08 | 2026-03-30 02:30:21.477958+04:00 | 2026-03-29 |
|   New York   |    US   |     11.51     |     9.89     |      45      |      7.72     |    few clouds    | 2026-03-29 22:29:57 | 2026-03-30 02:30:21.954610+04:00 | 2026-03-29 |
|    London    |    GB   |      6.47     |     5.83     |      82      |      1.34     | scattered clouds | 2026-03-30 05:34:14 | 2026-03-30 09:45:15.108489+04:00 | 2026-03-30 |
|   Karaköy    |    TR   |      8.78     |     5.02     |      98      |      8.23     |    light rain    | 2026-03-30 05:41:48 | 2026-03-30 09:45:15.646834+04:00 | 2026-03-30 |
| Cherni Gorod |    AZ   |     12.97     |    12.65     |      89      |      4.72     |  broken clouds   | 2026-03-30 05:40:53 | 2026-03-30 09:45:16.149379+04:00 | 2026-03-30 |
|    Japan     |    JP   |     20.27     |    19.97     |      62      |      6.69     |  broken clouds   | 2026-03-30 05:45:16 | 2026-03-30 09:45:16.685576+04:00 | 2026-03-30 |
|   New York   |    US   |      7.98     |     5.22     |      64      |      4.63     |    clear sky     | 2026-03-30 05:35:32 | 2026-03-30 09:45:17.212332+04:00 | 2026-03-30 |
+--------------+---------+---------------+--------------+--------------+---------------+------------------+---------------------+----------------------------------+------------+
Truncated to displaylimit of 10.

In [85]:
%%sql

INSERT INTO weather_daily_agg ( city, date , avg_temp_c, max_temp_c, avg_humidity)
SELECT
    city,
    DATE(recorded_at) as date,
    ROUND(AVG(temperature_c)::NUMERIC,2) as avg_temperature,
    MAX(temperature_c) as max_temperature,
    ROUND(AVG(humidity_pct)::NUMERIC,2) as avg_humidity
    

FROM weather_clean
WHERE DATE(recorded_at) = CURRENT_DATE
GROUP BY city, DATE(recorded_at)

ON CONFLICT (city, date)
     DO UPDATE SET
         avg_temp_c  = EXCLUDED.avg_temp_c,
         max_temp_c  = EXCLUDED.max_temp_c,
         min_temp_c  = EXCLUDED.min_temp_c,
         avg_humidity = EXCLUDED.avg_humidity

Running query in 'postgresql://rahimsharifov:***@localhost:5432/weather'

5 rows affected.

++
||
++
++

In [88]:
%%sql 

SELECT *
FROM weather_daily_agg

Running query in 'postgresql://rahimsharifov:***@localhost:5432/weather'

5 rows affected.

+--------------+------------+------------+------------+------------+--------------+
|     city     |    date    | avg_temp_c | max_temp_c | min_temp_c | avg_humidity |
+--------------+------------+------------+------------+------------+--------------+
| Cherni Gorod | 2026-03-30 |   12.97    |   12.97    |    None    |    89.00     |
|    Japan     | 2026-03-30 |   20.27    |   20.27    |    None    |    62.00     |
|   Karaköy    | 2026-03-30 |    8.78    |    8.78    |    None    |    98.00     |
|    London    | 2026-03-30 |    6.47    |    6.47    |    None    |    82.00     |
|   New York   | 2026-03-30 |    7.98    |    7.98    |    None    |    64.00     |
+--------------+------------+------------+------------+------------+--------------+